project:
  type: book

execute:
  enabled: true
  freeze: auto

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Fall 2026"
  author:
    - name: "[Jun Yan](https://statcomp.org) and Students in Fall 2026"
  date: today
  chapters:
    - index.qmd
    - chapters/data-acquisition.qmd
    - chapters/data-wrangling-visualization.qmd
    - chapters/statistical-modeling.qmd
    - chapters/advanced-methods-ai.qmd

format:
  html:
    html-math-method: mathjax
    theme: cosmo
